sudo: required
dist: trusty
language: python
install:
  - tools/spark-install ./spark
  - export PATH="$PATH:$(pwd)/spark/bin"
  - pyenv install 2.7.10
  - pyenv install 3.5.2
  - pyenv local 3.5.2 2.7.10
  - pip install tox
script:
  - sbt ++"$TRAVIS_SCALA_VERSION" assembly
  - sbt ++"$TRAVIS_SCALA_VERSION" publish-local
  - sbt ++"$TRAVIS_SCALA_VERSION" test
  - tox
